apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: overlay-for-vms
  namespace: system
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "overlay-for-vms",
    "type": "bridge",
    "bridge": "neon-br0",
    "ipam": {
      "type": "whereabouts",
      "ipRanges": [
        {
            "range": "10.100.0.0/16",
            "range_start": "10.100.128.0"
        },
        {
            "range": "fd10:100::/64"
        }
      ]
    }
  }'
